# Profile: production
spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      service: platform-service
      environment: production
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
