apiVersion: v1
kind: Secret
metadata:
  name: {{ include "travelo-backend.fullname" . }}-{{ .Values.service.name }}-secrets
  labels:
    {{- include "travelo-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  datasource-url: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  datasource-username: "{{ .Values.database.username }}"
  datasource-password: "{{ .Values.database.password }}"
  {{- if .Values.redis.password }}
  spring-data-redis-password: "{{ .Values.redis.password }}"
  {{- end }}

