{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "travelo-backend.fullname" . }}-{{ .Values.service.name }}-secrets
  labels:
    {{- include "travelo-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
